//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBTeknikServisEntities : DbContext
    {
        public DBTeknikServisEntities()
            : base("name=DBTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLArızaDetay> TBLArızaDetay { get; set; }
        public virtual DbSet<TBLDepartman> TBLDepartman { get; set; }
        public virtual DbSet<TBLFaturaBilgi> TBLFaturaBilgi { get; set; }
        public virtual DbSet<TBLFaturaDetay> TBLFaturaDetay { get; set; }
        public virtual DbSet<TBLGider> TBLGider { get; set; }
        public virtual DbSet<TBLKategori> TBLKategori { get; set; }
        public virtual DbSet<TBLMusteri> TBLMusteri { get; set; }
        public virtual DbSet<TBLNotlar> TBLNotlar { get; set; }
        public virtual DbSet<TBLPersonel> TBLPersonel { get; set; }
        public virtual DbSet<TBLSatıs> TBLSatıs { get; set; }
        public virtual DbSet<TBLUrun> TBLUrun { get; set; }
        public virtual DbSet<TBLUrunKabul> TBLUrunKabul { get; set; }
        public virtual DbSet<TBLUrunTakip> TBLUrunTakip { get; set; }
    
        public virtual ObjectResult<string> makskategoriurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("makskategoriurun");
        }
    }
}
