//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSatıs
    {
        public int SATISID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<short> ADET { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual TBLMusteri TBLMusteri { get; set; }
        public virtual TBLPersonel TBLPersonel { get; set; }
        public virtual TBLUrun TBLUrun { get; set; }
    }
}
